namespace Horsipelago.Models;
using System.Collections.Generic;

public static class AppleTracker
{
    public static readonly Dictionary<int, (string Name, string Region, bool Found)> Data = new()
    {
        { 71, ("Starting Apple", "Forest", false) },
        { 16, ("High Fire Ring", "Forest", false) },
        { 4, ("Left Vertical Tube", "Forest", false) },
        { 7, ("Right Vertical Tube", "Forest", false) },
        { 12, ("High Horizontal Tube", "Forest", false) },
        { 26, ("Crystal Apple 1", "Forest", false) },
        { 27, ("Crystal Apple 2", "Forest", false) },
        { 28, ("Crystal Apple 3", "Forest", false) },
        { 24, ("Fairy Ring", "Forest", false) },
        { 18, ("Behind Waterfall", "Forest", false) },
        { 3, ("Fairy Ring Diagonal Tube", "Forest", false) },
        { 8, ("Horse Trap Box", "Forest", false) },
        { 72, ("Gem's Horse Race", "Forest", false) },
        { 21, ("Low Fire Ring", "Forest", false) },
        { 15, ("Horse Race Diagonal Tube", "Forest", false) },
        { 20, ("High Small Diagonal Tube", "Forest", false) },
        { 29, ("Cave Entrance", "Forest", false) },
        { 39, ("Bear Apple", "Forest", false) },
        { 45, ("West Floating Island", "Forest", false) },
        { 6, ("East Floating Island", "Forest", false) },
        { 38, ("Wizard Apple 1", "Forest", false) },
        { 37, ("Wizard Apple 2", "Forest", false) },
        { 36, ("Wizard Apple 3", "Forest", false) },
        { 1, ("Lone Apple (Nature Lover)", "Forest", false) },
        { 17, ("On The Rocks", "Forest", false) },
        { 10, ("Stuck Between an Apple and a Hard Place", "Desert", false) },
        { 30, ("Apple Casino 1", "Desert", false) },
        { 31, ("Apple Casino 2", "Desert", false) },
        { 32, ("Apple Casino 3", "Desert", false) },
        { 83, ("Tumbleweed", "Desert", false) },
        { 2, ("An Apple is an Egg Right? (Nest)", "Desert", false) },
        { 84, ("Is that a seagull? (Bird Apple) (Bitch Ass Bird = B.A.B.)", "Desert", false) },
        { 42, ("Arch Apple (i use arch btw)", "Desert", false) },
        { 44, ("On the Arch Apple", "Desert", false) },
        { 0, ("Old Old Town Entrance", "Desert", false) },
        { 59, ("Shoot Horseboy", "Desert", false) },
        { 43, ("Jail", "Desert", false) },
        { 19, ("Top of Saloon", "Desert", false) },
        { 22, ("Top of Cactus", "Desert", false) },
        { 13, ("Fire Ring", "Desert", false) },
        { 5, ("Cactus Ring", "Desert", false) },
        { 35, ("Wait I'm Goated (Daredevil)", "Desert", false) },
        { 25, ("Underground Island", "Desert", false) },
        { 34, ("In between a stelagmite and a stelagtite (i cant spell", "Desert", false) },
        { 47, ("Chuck's Apple", "Desert", false) },
        { 9, ("Canyon Ledge", "Desert", false) },
        { 11, ("Between the Rocks", "Desert", false) },
        { 23, ("Trench Apple (Towards the north)", "Desert", false) },
        { 14, ("South Trench", "Desert", false) },
        { 33, ("Gorge Runner", "Desert", false) },
        { 60, ("Crane", "City", false) },
        { 62, ("Crane Cockpit", "City", false) },
        { 86, ("Subway", "City", false) },
        { 67, ("Subway Bathroom", "City", false) },
        { 66, ("West Low H Building", "City", false) },
        { 63, ("East Low H Building", "City", false) },
        { 64, ("west High H Building", "City", false) },
        { 65, ("east High H Building", "City", false) },
        { 53, ("Sewer Pipe", "City", false) },
        { 70, ("City's Edge (SE)", "City", false) },
        { 68, ("SE In Between Buildings", "City", false) },
        { 91, ("That Fucking Bird That I Hate", "City", false) },
        { 61, ("Eat This Apple? Sign", "City", false) },
        { 90, ("Top of Building (North)", "City", false) },
        { 69, ("Ledge of Building (North)", "City", false) },
        { 87, ("Cardboard Building North", "City", false) },
        { 88, ("Cardboard Building South", "City", false) },
        { 55, ("Parking Garage 1", "City", false) },
        { 56, ("Parking Garage 2", "City", false) },
        { 57, ("Parking Garage 3", "City", false) },
        { 89, ("Top of Building South", "City", false) },
        { 58, ("Ledge (West)", "City", false) },
        { 40, ("Water Overlook Pier Bridge Thingy", "City", false) },
        { 85, ("Doctor Evil", "City", false) },
        { 76, ("With the Tractors", "Farm", false) },
        { 77, ("In the Tractor", "Farm", false) },
        { 74, ("UFO Apple 1", "Farm", false) },
        { 52, ("UFO Apple 2", "Farm", false) },
        { 73, ("UFO Apple 3", "Farm", false) },
        { 51, ("God?", "Farm", false) },
        { 99, ("Swing", "Farm", false) },
        { 54, ("Dog House", "Farm", false) },
        { 82, ("Top of Silo", "Farm", false) },
        { 94, ("Over the Tube", "Farm", false) },
        { 81, ("Southwest Corn", "Farm", false) },
        { 93, ("Tractor Race", "Farm", false) },
        { 79, ("UFO Corn", "Farm", false) },
        { 78, ("Silo Corn", "Farm", false) },
        { 48, ("Horse Fan Club 1", "Farm", false) },
        { 49, ("Horse Fan Club 2", "Farm", false) },
        { 50, ("Horse Fan Club 3", "Farm", false) },
        { 46, ("The Sacrifice", "Farm", false) },
        { 75, ("Top of Barn", "Farm", false) },
        { 96, ("Upper Barn Rafters", "Farm", false) },
        { 97, ("Lower Barn Rafters 1", "Farm", false) },
        { 98, ("Lower Barn Rafters 2", "Farm", false) },
        { 92, ("Dentist", "Farm", false) },
        { 95, ("Behind Barn", "Farm", false) },
        { 80, ("North Corn", "Farm", false) },
        { 999, ("Golden Apple", "Glue", false) },
    };
}